sensor:
  - platform: rest
    resource: "http://nodered:1880/danalock/storage_room/get-state"
    name: Danalock
    timeout: 20
    scan_interval: 6000

rest_command:
  storage-room_lock:
    url: "http://nodered:1880/danalock/storage_room/lock"
    method: get
    timeout: 20
  storage-room_unlock:
    url: "http://nodered:1880/danalock/storage_room/unlock"
    method: get
    timeout: 20  
  storage-room_lock_status:
    url: "http://nodered:1880/danalock/storage_room/get-state"
    method: get
    timeout: 20